name: CI
on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2.3.0
      - run: npm install
      - run: npm run lint --if-present

  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 12, 14, 15 ]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run coverage --if-present
